server:
  http_listen_port: 3101
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # Change if needed

scrape_configs:
  - job_name: my-python-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: my-python-app
          __path__: /logs/*.log
